server:
  port: 8085

spring:
  application:
    name: config-sv
  cloud:
    config:
      server:
        git:
          uri: https://github.com/francodavyd/Microservices-2.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${PASSWORD}